// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_C_.Database;

#nullable disable

namespace Web_C_.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20230416115257_update")]
    partial class update
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_C_.Database.Data.ProductDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Price", "Name", "Amount");

                    b.ToTable("Products");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ProductDto");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Web_C_.Database.Data.UserDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasAlternateKey("Email", "Phone");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Web_C_.DAL.Model.TypeProducts.PhoneDto", b =>
                {
                    b.HasBaseType("Web_C_.Database.Data.ProductDto");

                    b.HasDiscriminator().HasValue("PhoneDto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 10,
                            Description = "Samsung Galaxy A23 – отличный пример современного функционального смартфона, который обеспечивает хорошую производительность, более чем достойную автономность и не помешает превратить яркий момент в незабываемый кадр. Он получил современный дисплей с частотой обновления до 90 Гц и разрешением FHD+, восьмиядерный процессор и достойный запас оперативной памяти и хранилища.",
                            Name = "Samsung Galaxy A23 4/64 ГБ, черный",
                            Price = 45780m
                        },
                        new
                        {
                            Id = 2,
                            Amount = 5,
                            Description = "Смартфон Galaxy A32 оснащён гибко настраиваемым экраном «Always On Display» - вместо обычного индикатора уведомлений, вы получаете возможность пользоваться базовыми функциями и считывать необходимую информацию из выключенного экрана, что также помогает экономить лишний расход заряда батареи.",
                            Name = "Samsung Galaxy A23 4/64 ГБ, черный",
                            Price = 25670m
                        },
                        new
                        {
                            Id = 3,
                            Amount = 20,
                            Description = "iPhone 14 Pro (6.1\") противоударный Прозрачный купить в Москве дешево с доставкой. Чехол-накладка силикон Deppa Gel Shockproof Case D-88325 для iPhone 14 Pro (6.1\") противоударный Прозрачный – продажа по низкой цене с гарантией. Фото, технические характеристики, отзывы, аксессуары, видео – все это поможет вам определиться с выбором.",
                            Name = "Apple iPhone 11 64GB Black (черный) A2221",
                            Price = 15490m
                        },
                        new
                        {
                            Id = 4,
                            Amount = 50,
                            Description = "Лучший дисплей iPhone с невероятной контрастностью и более высоким разрешением. И передняя панель Ceramic Shield, с которой риск повреждений дисплея при падении в четыре раза ниже.",
                            Name = "Apple iPhone 14 Pro Max 1Tb Deep Purple (тёмно-фиолетовый) A2894",
                            Price = 143999m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
